### ISSUE TITLE
Error - Capistraon Load File error -- capistrano/cli (LoadError)

### ISSUE THREAD

**Issue by UsmanMalik** [capistrano/rails#164]
Hi , i am trying to deploy rails server for the first time. Using this article

https://gorails.com/deploy/ubuntu/14.04#capistrano

Now i am stuck at this 

I ran this command after set **Adding The Nginx Host**
cap production deploy

and ran into this, now no idea what to do. 

/home/deploy/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- capistrano/cli (LoadError)
	from /home/deploy/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/bin/cap:3:in `<main>'

**Comment by mattbrictson** [comment]
Hi, judging by your backtrace you are trying to run Capistrano v2, but the tutorial calls for v3. Somehow you have installed multiple versions of Capistrano on your computer, which is causing this trouble.

I suggest you run Capistrano by prefixing all your cap command with `bundle exec`: e.g. `bundle exec cap production deploy`. This will ensure the correct version of Capistrano is used, as specified in your Gemfile.

Good luck!


--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by UsmanMalik** [comment]
Thanks but it did not help.

I asked the same question on stackoverflow
http://stackoverflow.com/questions/35332766/rails-deployment-capistrano-capistrano-cli-loaderror
