### ISSUE TITLE
What defines order of migrate & asset tasks?

### ISSUE THREAD

**Issue by ttrmw** [capistrano/rails#180]
Hey,

I see both the asset and migration tasks run `after deploy:updated`, but what defines which will be run first? 

The flow document [here](http://capistranorb.com/documentation/getting-started/flow/) suggests that with the migrate and asset plugins, migration will occur first, but with the rails plugin we're observing the opposite. 

I notice that the order of the requires for these plugins is [reversed in this project](https://github.com/capistrano/rails/blob/master/lib/capistrano/rails.rb) when compared to the [requires in the flow document](http://capistranorb.com/documentation/getting-started/flow/#flow-examples) and was wondering if this was the cause? 

if so, I think parity would be helpful - whether that means a docs fix over there or a change to the requires over here.

**Comment by mattbrictson** [comment]
Good catch! Yes, I would consider the ordering in the capistrano-rails gem to be the "correct" order. Specifically:

```ruby
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
```

I'm not sure the order really matters in practice, but for consistency I agree the web documentation should be updated to match.

If you are up for it, I would really appreciate a PR to fix the docs, which you can do in the documentation repository here: https://github.com/capistrano/documentation

Otherwise please log an issue in that same repo so that another contributor can make the fix.

Thanks!

**Comment by ttrmw** [comment]
Happily! 

My specific issue was that a previous maintainer of my project used asset compilation for an after hook that in some cases would require the migrations to have run, so the docs order would have been preferable (and I assume is what led them to use that hook). But as you say it shouldn't make any difference, given parity with the docs.

**Comment by mattbrictson** [comment]
Closing now that https://github.com/capistrano/documentation/issues/198 is merged.
