### ISSUE TITLE
No Dependence on Rails in Gemspec

### ISSUE THREAD

**Issue by kyledecot** [capistrano/rails#194]
When looking at `capistrano-rails.gemspec` I expected to see something like:

```ruby
gem.add_dependency 'rails', '> x.x.x'
```

This however doesn't seem to be the case as there are no mentions of rails in said file. Is this something that should be included or is this intentionally left out?

**Comment by mattbrictson** [comment]
It is intentionally left out. This project does not actually depend on Rails. That is, we never actually `require` or `load` any Rails code.

It is possible, for example, to keep your Rails app and the Capistrano scripts used to deploy that app in two separate repositories (or Gemfiles). The Capistrano scripts don't require Rails to be present in order to perform the deployment.

**Comment by kyledecot** [comment]
Thanks for clearing that up @mattbrictson
