### ISSUE TITLE
Can't deploy to staging

### ISSUE THREAD

**Issue by magicalbanana** [capistrano/rails#198]
No matter what I do it's always deploying to production. I have set `rails_env` and no avail. Even my puma process is running in production.

Any thoughts?

**Comment by mattbrictson** [comment]
Hi, I know you are stuck but GitHub is not the right forum for these types of questions. Could you take your question to Stack Overflow? I also suggest running `cap staging doctor` for additional information that will help you troubleshoot.

--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by magicalbanana** [comment]
Thanks for the reply. I figured it out actually, I simply used a string instead of a symbol when setting the `rails_env`.
