### ISSUE TITLE
Rails 7 + Capistrano

### ISSUE THREAD

**Issue by gscoders** [capistrano/rails#252]
If with new default importmap gem in Rails 7 assets:precompile process with take a lot of time will be faster or even will not exists?

**Comment by mattbrictson** [comment]
I am pretty sure `assets:precompile` will still be necessary. I am speculating because I haven't used it yet, but my understanding is that CSS is completely separate, and will continue being bundled by the asset pipeline. In which case `assets:precompile` is still a necessary and important step for deploying to production.

You can also see that the `importmap-rails` hooks directly into the asset pipeline. This tells me that `assets:precompile` is required.

https://github.com/rails/importmap-rails/blob/411aa772aaabb4344b0bbb1f4e6a25b2dbba50af/lib/importmap/engine.rb#L18-L23

As to whether it will be faster: I have no idea. 😄
